var namespacemage =
[
    [ "AABB", "structmage_1_1_a_a_b_b.html", "structmage_1_1_a_a_b_b" ],
    [ "ConditionVariable", "classmage_1_1_condition_variable.html", "classmage_1_1_condition_variable" ],
    [ "Edge", "structmage_1_1_edge.html", "structmage_1_1_edge" ],
    [ "Engine", "classmage_1_1_engine.html", "classmage_1_1_engine" ],
    [ "EngineSetup", "structmage_1_1_engine_setup.html", "structmage_1_1_engine_setup" ],
    [ "Face", "structmage_1_1_face.html", "structmage_1_1_face" ],
    [ "GeneralConfiguration", "structmage_1_1_general_configuration.html", "structmage_1_1_general_configuration" ],
    [ "IndexedEdge", "structmage_1_1_indexed_edge.html", "structmage_1_1_indexed_edge" ],
    [ "IndexedFace", "structmage_1_1_indexed_face.html", "structmage_1_1_indexed_face" ],
    [ "LinkedList", "classmage_1_1_linked_list.html", "classmage_1_1_linked_list" ],
    [ "LVertex", "structmage_1_1_l_vertex.html", "structmage_1_1_l_vertex" ],
    [ "MemoryArena", "classmage_1_1_memory_arena.html", "classmage_1_1_memory_arena" ],
    [ "Mutex", "classmage_1_1_mutex.html", "classmage_1_1_mutex" ],
    [ "MutexLock", "structmage_1_1_mutex_lock.html", "structmage_1_1_mutex_lock" ],
    [ "ProgressReporter", "classmage_1_1_progress_reporter.html", "classmage_1_1_progress_reporter" ],
    [ "ReadWriteMutex", "classmage_1_1_read_write_mutex.html", "classmage_1_1_read_write_mutex" ],
    [ "ReadWriteMutexLock", "structmage_1_1_read_write_mutex_lock.html", "structmage_1_1_read_write_mutex_lock" ],
    [ "Reference", "classmage_1_1_reference.html", "classmage_1_1_reference" ],
    [ "ReferenceCounted", "classmage_1_1_reference_counted.html", "classmage_1_1_reference_counted" ],
    [ "Resource", "classmage_1_1_resource.html", "classmage_1_1_resource" ],
    [ "ResourceManager", "classmage_1_1_resource_manager.html", "classmage_1_1_resource_manager" ],
    [ "Semaphore", "classmage_1_1_semaphore.html", "classmage_1_1_semaphore" ],
    [ "Task", "classmage_1_1_task.html", "classmage_1_1_task" ],
    [ "Timer", "classmage_1_1_timer.html", "classmage_1_1_timer" ],
    [ "TLVertex", "structmage_1_1_t_l_vertex.html", "structmage_1_1_t_l_vertex" ],
    [ "Vertex", "structmage_1_1_vertex.html", "structmage_1_1_vertex" ]
];